In [1]:
import numpy as np

In [4]:
myList = [1,2,3,5]
arr1 = np.array(myList)

In [5]:
arr2 = np.array([[1,2,4,5],[7,8,99,89]])

In [6]:
arr1.shape

(4,)

In [7]:
arr2.shape

(2, 4)

In [8]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.empty(5)

array([2.45845484e-316, 6.92789186e-310, 0.00000000e+000, 6.92805261e-310,
       2.37151510e-322])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr3 = np.array([1,2,6,8])

In [13]:
arr = arr1+arr3

In [14]:
arr

array([ 2,  4,  9, 13])

In [15]:
ar =arr1 -arr3

In [16]:
ar

array([ 0,  0, -3, -3])

In [19]:
arr1 * 3

array([ 3,  6,  9, 15])

In [21]:
arr1**2

array([ 1,  4,  9, 25])

In [22]:
arr1[3]

5

In [23]:
arr1[2:3]

array([3])

In [24]:
arr_copy = arr.copy()

In [25]:
arr_copy

array([ 2,  4,  9, 13])

In [28]:
arr2[1][1]

8

In [29]:
arr2[:2][:1]

array([[1, 2, 4, 5]])